scrapers:
  - name: JazzCafeAlto
    url: http://www.jazz-cafe-alto.nl/
    item: div.entry-content > div.event-list > ul.event-list-view > li.event
    fields:
      - name: "location"
        value: "Jazz Café Alto"
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "http://www.jazz-cafe-alto.nl/"
      - name: title
        type: text
        location:
          - selector: div.event-info.single-day:nth-child(2) > div.event-title > h3 > a
      - name: url
        type: url
        location:
          - selector: div.event-info.single-day:nth-child(2) > div.event-title > h3 > a
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.event-info.single-day > div.event-details > p > a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.event-info.single-day:nth-child(2) > span.event-time
              regex_extract:
                exp: "[0-9]{2}\\.[0-9]{2}"
            layout:
              - "15.04"
          - covers:
              year: true
            location:
              selector: div.event-date > div.start-date > div.event-year:nth-child(4)
            layout:
              - "2006"
          - covers:
              month: true
            location:
              selector: div.event-date > div.start-date > div.event-month:nth-child(3)
            layout:
              - Jan
          - covers:
              day: true
            location:
              selector: div.event-date > div.start-date > div.event-day:nth-child(2)
            layout:
              - "2"
        date_location: CET
        date_language: en_US

  - name: BourbonStreet
    url: https://www.bourbonstreet.nl/shows
    item: div#wix-events-widget > div > ul > li
    fields:
      - name: "location"
        value: "Bourbon Street"
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.bourbonstreet.nl/shows
      - name: url
        type: url
        location:
          - selector: a[data-hook="ev-rsvp-button"]
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: wow-image > img
            attr: src
        transform:
          # unblur some weird blured image url
          - type: regex-replace
            regex: "w_147.*enc_auto"
            replace: "w_100,h_100,fp_0.50_0.50,q_80,usm_0.66_1.00_0.01,enc_auto"
      - name: title
        type: text
        location:
          - selector: span[data-hook="ev-list-item-title"]
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div[data-hook="date"]
              regex_extract:
                exp: "[0-9]{1,2} [A-Za-z]{3} [0-9]{4}, [0-9]{2}:[0-9]{2}"
                index: 0
            layout:
              - 2 Jan 2006, 15:04
        date_location: CET
        date_language: en_US

  - name: Bimhuis
    url: https://www.bimhuis.nl/agenda
    item: ul.agenda-tile-overview.agenda-tile-overview--list > li.agenda-tile-overview__item > div.agenda-tile
    fields:
      - name: "location"
        value: Bimhuis
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.bimhuis.nl/agenda
      - name: comment
        type: text
        location:
          - selector: div.agenda-tile__content.agenda-tile__content-nl > div > div > p.NRmTR_lljAoM
      - name: title
        type: text
        location:
          - selector: div.agenda-tile__content.agenda-tile__content-nl > div > div > a.agenda-tile__link > h3.PJCQ_bnIF
      - name: url
        type: url
        location:
          - selector: div.agenda-tile__content.agenda-tile__content-nl > div > div > a.agenda-tile__link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.agenda-tile__img-tile > figure.AxKgX_gvVear.agenda-tile__img-container > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.agenda-tile__content.agenda-tile__content-nl > div > time.agenda-tile__dates > span
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.agenda-tile__content.agenda-tile__content-nl > div > time.agenda-tile__dates
            layout:
              - Mon 2 January 2006
        date_location: CET
        date_language: nl_BE
    fetcher:
      type: dynamic
    interaction:
      - type: scroll
        delay: 2000
      - type: scroll
        delay: 2000
      - type: scroll
        delay: 2000
      - type: scroll
        delay: 2000

  - name: Bitterzoet
    url: https://www.bitterzoet.com/agenda/
    item: div.agenda-page__agenda-item > div.agenda-item.agenda-item--lg
    fields:
      - name: "location"
        value: Bitterzoet
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.bitterzoet.com/agenda/
      - name: url
        type: url
        location:
          - selector: div.agenda-item__container--text > a
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: a > div.agenda-item__image
            attr: style
            regex_extract:
              exp: "https://[^)]+"
      - name: title
        type: text
        location:
          - selector: a > div.agenda-item__title:nth-child(4) > div.title-component
      - name: genresText
        type: text
        location:
          - selector: a > div.agenda-item__subtitle:nth-child(5)
        can_be_empty: true
      - name: comment
        type: text
        location:
          - selector: a > div.agenda-item__subtitle:nth-child(5)
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: a > div.agenda-item__date-time-price.agenda-item__date-time-price--phone:nth-child(2)
            layout:
              - Monday 2 January  2006 / 15:04
        date_location: CET
        date_language: nl_BE
    fetcher:
      type: dynamic

  - name: MaloeMelo
    url: https://www.maloemelo.com/events/
    item: div > div > div > div > div > div > div.tribe-events-calendar-list > div.tribe-events-calendar-list__event-row
    fields:
      - name: "location"
        value: Maloe Melo
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.maloemelo.com/events/
      - name: title
        type: text
        location:
          - selector: header.tribe-events-calendar-list__event-header > h3.tribe-common-h4--min-medium.tribe-common-h6.tribe-events-calendar-list__event-title > a.tribe-common-anchor-thin.tribe-events-calendar-list__event-title-link
      - name: comment
        type: text
        location:
          - selector: div.tribe-common-a11y-hidden.tribe-common-b2.tribe-events-calendar-list__event-description > p
        can_be_empty: true
      - name: url
        type: url
        location:
          - selector: header.tribe-events-calendar-list__event-header > h3.tribe-common-h4--min-medium.tribe-common-h6.tribe-events-calendar-list__event-title > a.tribe-common-anchor-thin.tribe-events-calendar-list__event-title-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.tribe-events-calendar-list__event-featured-image-wrapper.tribe-common-g-col > a > img
            attr: src
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              time: true
            location:
              selector: header.tribe-events-calendar-list__event-header > div.tribe-common-b2.tribe-events-calendar-list__event-datetime-wrapper > time.tribe-events-calendar-list__event-datetime > span.tribe-event-date-start
            layout:
              - January 2 @ 15:04
        date_location: CET
        date_language: en_US

  - name: DeNieuweAnita
    url: https://denieuweanita.nl/
    item: "#us_grid_2 > div.w-grid-list > article.agenda"
    fields:
      - name: "location"
        value: De Nieuwe Anita
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://denieuweanita.nl/
      - name: title
        type: text
        location:
          - selector: div > h2.w-post-elm.post_title.usg_post_title_1.entry-title
      - name: url
        type: url
        location:
          - selector: a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.w-post-elm.post_custom_field.usg_post_custom_field_3.type_text.agenda_time_start.color_link_inherit > span
              default: "20:00"
            layout:
              - 15:04
          - covers:
              day: true
              month: true
            location:
              selector: div.w-post-elm.post_custom_field.usg_post_custom_field_2.type_text._space_yearless_date.color_link_inherit > span
            layout:
              - 2 Jan
        date_location: CET
        date_language: en_US
        guess_year: true

  # this venue website would benefit from a scrolling function to be able to scrape more events
  - name: Paradiso
    url: https://www.paradiso.nl/nl/
    item: div.css-16y59pb a.css-1agutam
    fields:
      - name: "city"
        value: "Amsterdam"
      - name: "country"
        value: "Netherlands"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.paradiso.nl/nl/
      - name: title
        type: text
        location:
          - selector: h2.chakra-heading
      - name: comment
        type: text
        location:
          - selector: p.chakra-text
      - name: genresText
        type: text
        location:
          - selector: p.chakra-text
      - name: url
        type: url
        location:
          - attr: href
      - name: location
        on_subpage: url
        location:
          selector: div.css-8itx08 > div.css-7po6wk > div > div > div.css-65enbk > p:nth-child(2)
          entire_subtree: true
          regex_extract:
            exp: "[A-Za-z]+"
            index: 1
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
            location:
              selector: body > main > div > div.css-1n97teq > div > div > div.css-e46pf6 > div > div.css-8itx08 > div.css-7po6wk > div > div > div.css-65enbk > p.chakra-text.css-tkkldl
            layout: ["Monday 2 January"]
          - covers:
              time: true
            location:
              selector: body > main > div > div.css-1n97teq > div > div > div.css-e46pf6 > div > div.css-8itx08 > div.css-7po6wk > div > div > div.css-65enbk > p:nth-child(3)
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
                index: -1
            layout: ["15:04"]
        date_language: nl_BE
        date_location: CET
        guess_year: true
    fetcher:
      type: dynamic
    filters:
      - field: location
        exp: Bitterzoet # already covered by a different scraper
        match: false
