scrapers:
  - name: Bierhuebeli
    url: "https://bierhuebeli.ch/konzerte/"
    #wpv-view-layout-21772-CATTRf804edd54c7df1da97942dc63264639b > a:nth-child(15)
    item: div.elementor-shortcode > div > a.datumlink
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Bierhuebeli"
      - name: "sourceUrl"
        value: "https://bierhuebeli.ch/konzerte/"
      - name: url
        type: url
        location:
          attr: href
      - name: title
        type: text
        location:
          selector: div.eventtitel
      - name: tag
        type: text
        location:
          selector: div.eventtag24.normaltags
        can_be_empty: true
      - name: comment
        type: text
        can_be_empty: true
        location:
          selector: div.billing-part > div.byline > font
          entire_subtree: true
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            layout: ["2.1.2006"]
            location:
              selector: div.eventdatum25
              regex_extract:
                exp: "[0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{4}"
          - covers:
              time: true
            location:
              selector: div.eventheadline2.headlinecolorgrey
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
                index: -1
            layout: ["15:04"]
        date_language: de_DE
        date_location: "Europe/Berlin"
    filters:
      - field: tag
        exp: "Abgesagt"
        match: false

  - name: Gaskessel
    url: https://gaskessel.ch/programm/
    item: article.eventpreview
    fields:
      - name: "location"
        value: "Gaskessel"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://gaskessel.ch/programm/"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: a.previewlink > span.eventdatum
            layout: ["Mon 2.1.06"]
          - covers:
              time: true
            location:
              selector: div.contentbox > div.content > div.textblock > div.infobox > div.table > div.trow > div.tcell:nth-child(2)
            layout: ["15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: title
        type: text
        location:
          selector: a.previewlink > h2.eventname
          entire_subtree: true
      - name: url
        type: url
        location:
          selector: div.contentbox > div.content > div.textblock > div.infobox > div.btns > a.ticketlink
          attr: href
      - name: comment
        type: text
        location:
          selector: div.contentbox > div.content > div.textblock > div.text > p
        can_be_empty: true
      - name: genresText
        type: text
        location:
          selector: span.eventgenre
        can_be_empty: true

  - name: Dachstock
    url: https://www.dachstock.ch/events
    item: div.event-teaser-info
    fields:
      - name: "location"
        value: "Dachstock"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.dachstock.ch/events
      - name: "date"
        type: "date"
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: a.event-date
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}.[0-9]{4} - [0-9]{2}:[0-9]{2}"
            layout: ["02.01.2006 - 15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: "url"
        type: url
        location:
          selector: div.event-teaser-top > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: div.artist-name
          all_nodes: true
          separator: ", "
      - name: "comment"
        type: text
        location:
          selector: div.event-title
        can_be_empty: true

  - name: MahoganyHall
    url: https://www.mahogany.ch/konzerte
    item: div.view.view-display-id-page_1.view-id-konzerte.view-konzerte > div.view-content > div.views-row
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Mahogany Hall"
      - name: "sourceUrl"
        value: "https://www.mahogany.ch/konzerte"
      - name: comment
        type: text
        location:
          - selector: div.views-field.views-field-field-teasertext > div.field-content > p
      - name: title
        type: text
        location:
          - selector: div.views-field.views-field-title > h2.field-content > a
      - name: url
        type: url
        location:
          - selector: div.views-field.views-field-title > h2.field-content > a
            attr: href
      - name: genresText
        type: text
        location:
          - selector: div.views-field.views-field-field-subtitle > h5.field-content
            entire_subtree: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.views-field.views-field-field-tueroeffnung > div.field-content > time.datetime
            layout:
              - Monday, 2. January 2006 | 15.04 Uhr
        date_location: CET
        date_language: de_DE

  - name: ISC
    url: https://isc-club.ch/
    item: div.event_listing > a
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "ISC Club"
      - name: "sourceUrl"
        value: "https://isc-club.ch/"
      - name: title
        type: text
        location:
          - selector: div.event_title_two_colums.inside_content.max_width_box > div.column_right:nth-child(2) > div.event_title_title:nth-child(3)
      - name: style
        type: text
        location:
          - selector: div.event_title_two_colums.inside_content.max_width_box > div.column_right:nth-child(2) > div.event_title_info:nth-child(2)
      - name: date
        type: date
        components:
          - covers:
              year: true
              month: true
              day: true
              time: true
            location:
              selector: var.atc_date_start
            layout: ["2006-01-02 15:04:00"]
        on_subpage: url
        date_language: de_DE
        date_location: "Europe/Berlin"
      - name: url
        type: url
        location:
          - attr: href
      - name: imageUrl
        type: url
        on_subpage: url
        location:
          - selector: "div.fullscreen_event_bg.filter_none"
            attr: data-bgset
            regex_extract:
              exp: "[^ ]+"
              index: 0
        can_be_empty: true

  - name: OnoBern
    url: https://www.onobern.ch/homepage/
    item: body > div > div.et-boc > div > div > article.hentry.page.post-19.status-publish.type-page > div.entry-content > div.et-l.et-l--post > div.et_builder_inner_content.et_pb_gutters3 > div.et_pb_section.et_pb_section_1.et_section_regular > div.et_pb_row.et_pb_row_3 > div.et-last-child.et_pb_column.et_pb_column_2.et_pb_column_4_4.et_pb_css_mix_blend_mode_passthrough > div.et_pb_bg_layout_light.et_pb_module.et_pb_text.et_pb_text_1.et_pb_text_align_left > div.et_pb_text_inner > div.ajde_evcal_calendar.box_2.list_cal.ul > div.evcal_list_month.eventon_events_list.sep_months > div.sep_month_events > div.event.eventon_list_event.evo_eventtop
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "ONO Das Kulturlokal"
      - name: "sourceUrl"
        value: "https://www.onobern.ch/homepage/"
      - name: comment
        type: text
        location:
          - selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_desc.evo_info.hide_eventtopdata:nth-child(3) > span.evo_below_title:nth-child(3) > span.evcal_event_subtitle
      - name: title
        type: text
        location:
          - selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_desc.evo_info.hide_eventtopdata:nth-child(3) > span.evcal_desc2.evcal_event_title:nth-child(2)
      - name: date
        type: date
        components:
          - covers:
              year: true
            location:
              selector: #evcal_cur
              regex_extract:
                exp: "[0-9]{4}"
            layout: ["2006"]
          - covers:
              month: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.month:nth-child(3)
            layout: ["Jan.", "January"]
          - covers:
              day: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.date:nth-child(2)
            layout: ["02"]
          - covers:
              time: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.time:nth-child(4)
            layout: ["15:04"]
        date_language: de_DE
        date_location: "Europe/Berlin"
      - name: url
        type: url
        location:
          - selector: div.evo_event_schema > a
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: .ev_ftImg
            attr: data-img
    filters:
      - field: comment
        exp: "Privat"
        match: false
