scrapers:
  - name: LocomotivClub
    url: "https://www.locomotivclub.it/eventtype/calendario/"
    item: ".qt-item-event"
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bologna"
      - name: "location"
        value: "Locomotiv Club"
      - name: "sourceUrl"
        value: "https://www.locomotivclub.it/eventtype/calendario/"
      - name: "title"
        location:
          selector: ".qt-text-shadow"
      - name: "comment"
        location:
          selector: ".qt-the-content div"
        can_be_empty: true
        on_subpage: "url"
      - name: "url"
        type: "url"
        location:
          selector: ".qt-text-shadow"
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: ".qt-eventtable tr td"
              regex_extract:
                exp: "Data:.*"
              entire_subtree: true
            layout: ["Data: 2 January 2006"]
          - covers:
              time: true
            location:
              selector: ".qt-eventtable tr:nth-child(3) td"
              regex_extract:
                exp: "Inizio ore: .*"
              entire_subtree: true
            layout: ["Inizio ore: 3:04 pm"]
        date_location: "Europe/Berlin"
        date_language: "it_IT"
    filters:
      - field: "title"
        exp: ".*CANCELED.*"
        match: false
      - field: "title"
        exp: "ANNULLATO!.*"
        match: false
      - field: "title"
        exp: ".*Postponed.*"
        match: false
    paginator:
      location:
        selector: ".pagination li:nth-child(2) .qt-btn-primary"
      max_pages: 2

  - name: MercatoSonato
    url: https://www.senzaspine.org/centro-culturale#anchor-eventi-mercato
    item: div.eventi-section > div.collection-list-wrapper-9.w-dyn-list > div.collection-list-evenit-scuola.w-dyn-items > div.collection-item-3.w-dyn-item
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bologna"
      - name: country
        value: Italy
      - name: "location"
        value: "Mercato Sonato"
      - name: "sourceUrl"
        value: https://www.senzaspine.org/centro-culturale#anchor-eventi-mercato
      - name: title
        type: text
        location:
          - selector: div.eventi-box-content > div.titolo-descrizione > h3.eventi-orchestra-title.h3-styles
      - name: url
        type: url
        location:
          - selector: a.eventi-box-image.w-inline-block
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div:nth-child(5)
            layout:
              - "15:04"
          - covers:
              year: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass:nth-child(3)
            layout:
              - "2006"
          - covers:
              day: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass
            layout:
              - "2"
          - covers:
              month: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass:nth-child(2)
            layout:
              - January
        date_location: CET
    paginator:
      location:
        selector: "div.pagination > a.w-pagination-next"
      max_pages: 6
