scrapers:
  - name: Albani
    url: https://www.albani.ch/de/programm.html
    item: div.accWrap
    fields:
      - name: "location"
        value: "Albani"
      - name: "city"
        value: "Winterthur"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.albani.ch/de/programm.html"
      - name: url
        type: url
        location:
          - selector: div > a
            attr: data-acc-ref
      - name: title
        type: text
        location:
          - selector: div.albani-event-label > span
            all_nodes: true
            separator: " "
      - name: genresText
        type: text
        location:
          - selector: div.albani-event-label > span.subline
        can_be_empty: true
      - name: comment
        type: text
        location:
          - selector: div.albani-event-textblock > p
            all_nodes: true
            separator: "\n"
        can_be_empty: true
      - name: imageUrl
        type: url
        location:
          - selector: img
            attr: data-src
      - name: date
        type: date
        guess_year: true
        components:
          - covers:
              day: true
              month: true
            location:
              selector: div.albani-event-date > span.date
            layout: ["Mon 02.01"]
          - covers:
              time: true
            location:
              selector: div.albani-event-date > span.subline
            layout: ["15:04 UHR"]
        date_location: CET
        date_language: de_DE
    fetcher:
      type: static

  - name: ESSE
    url: https://www.esse-musicbar.ch/index.php/veranstaltungen/live-veranstaltiungen
    item: div.ic-list-event
    fields:
      - name: "location"
        value: "ESSE"
      - name: "city"
        value: "Winterthur"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.esse-musicbar.ch"
      - name: url
        type: url
        location:
          - selector: a
            attr: href
      - name: title
        type: text
        location:
          - selector: a
            attr: title
      - name: comment
        type: text
        on_subpage: url
        location:
          - selector: div.ic-full-description > p
            all_nodes: true
            separator: "\n"
        can_be_empty: true
      - name: imageUrl
        type: url
        on_subpage: url
        location:
          - selector: div.image.ic-image > img
            attr: src
        can_be_empty: true
      - name: genresText
        type: text
        location:
          - selector: div.ic-title-cat > a
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: span.ic-single-next, span.ic-period-startdate, span.ic-single-startdate
            transform:
              - type: regex-replace
                regex: "[^A-Za-z0-9,.ä]+"
                replace: " "
            layout: ["Monday, 2. January 2006"]
          - covers:
              time: true
            location:
              selector: span.ic-single-starttime, span.ic-period-starttime
            layout: ["15:04"]
        date_location: CET
        date_language: de_DE
    fetcher:
      type: static
    paginator:
      location:
        selector: "#icagenda-list > div:nth-child(5) > div > div.ic-next > a"
    filters:
      - field: title
        exp: "Kulinarische Mittagspause"
        match: false
      - field: title
        exp: "Privatanlass"
        match: false

  - name: Salzhaus
    url: "https://www.salzhaus.ch/de/programm.html"
    item: ".sHprogramm"
    fields:
      - name: "location"
        value: "Salzhaus"
      - name: "city"
        value: "Winterthur"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.salzhaus.ch/de/programm.html"
      - name: "title"
        location:
          selector: ".sHInfo a"
      - name: "imageUrl"
        type: url
        location:
          selector: ".sHImg > a > img"
          attr: data-src
      - name: "comment"
        location:
          selector: ".sHInfo h2"
        can_be_empty: true
      - name: "url"
        type: "url"
        location:
          selector: ".sHInfo a"
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: "div.sHDetailRow:nth-child(2) span:nth-child(2)"
              regex_extract:
                exp: "([0-9]{1,2}\\.){2}[0-9]{4}"
                index: 0
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              selector: "div.sHDetailRow:nth-child(3) span:nth-child(2)"
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: ["15:04"]
        date_location: "Europe/Berlin"

  - name: Musikfestwochen
    url: https://musikfestwochen.ch/programm/programm-nach-datum/
    item: main.columns.first.large-8.medium-8 > section.programmlist-container > article.act-item.info-invisible
    fields:
      - name: "city"
        value: "Winterthur"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://musikfestwochen.ch/programm/programm-nach-datum/
      - name: comment
        type: text
        location:
          - selector: div.programm-infos > div:nth-child(7)
        can_be_empty: true
      - name: location
        type: text
        location:
          - selector: div.programm-infos > h5:nth-child(3)
      - name: url
        type: url
        location:
          - selector: div.columns.large-4.medium-6.small-12 > a
            attr: href
      - name: title
        type: text
        location:
          - selector: div.row > div.columns.large-10.medium-8 > a > h3
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.act-extend.row:nth-child(2) > div:nth-child(2) > div.programm-infos > h5
            layout:
              - Monday, 2. January 2006, 15:04
              - Monday, 2 January 2006, 15:04
              - Monday 2. January 2006, 15:04
        date_location: CET
    filters:
      - field: date
        exp: "> now"
        match: true

  - name: BarLabuesch
    url: https://bar.labuesch.ch/#events
    item: div.wb-anim.wb-anim-zoom-in.wb-store-item
    fields:
      - name: "city"
        value: "Winterthur"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "location"
        value: "Labuesch Bar"
      - name: "sourceUrl"
        value: https://bar.labuesch.ch/#events
      - name: title
        type: text
        location:
          - selector: div.wb-store-name > a
            regex_extract:
              exp: "[^-]+"
              index: 1
      - name: url
        type: url
        location:
          - selector: div.wb-store-name > a
            attr: href
      - name: comment
        type: text
        on_subpage: "url"
        location:
          - selector: div > div > div.wb-store-properties > div.wb-store-desc > div:nth-child(2)
            entire_subtree: true
      - name: date
        type: date
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div > div > div.wb-store-properties > table > tbody
              entire_subtree: true
              regex_extract:
                exp: "([0-9]{2}\\.){2}[0-9]{4}"
                index: 0
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              selector: div > div > div.wb-store-properties > table > tbody
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2}\\.[0-9]{2} Uhr"
                index: 1
            layout: ["15.04 Uhr"]
        date_location: "Europe/Zurich"
      - name: imageUrl
        type: url
        location:
          - selector: div.wb-store-thumb > a > img
            attr: src
    fetcher:
      type: static
    filters:
      - field: title
        exp: "Tanzkurs"
        match: false

  - name: Kraftfeld
    url: https://www.kraftfeld.ch/de/programm.html
    item: article.kf-listitem
    fields:
      - name: "location"
        value: "Kraftfeld"
      - name: "city"
        value: "Winterthur"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.kraftfeld.ch/de/programm.html"
      - name: title
        type: text
        location:
          - attr: title
            regex_extract:
              exp: "[^|]+"
              index: 0
      - name: url
        type: url
        location:
          - attr: data-url
      - name: imageUrl
        type: url
        on_subpage: url
        location:
          - selector: .kf-image > a > img
            attr: data-src
        can_be_empty: true
      - name: comment
        type: text
        on_subpage: url
        location:
          - selector: div.kf-text > p
            all_nodes: true
            separator: "\n"
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              attr: title
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}.[0-9]{4}$"
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              default: "23:00"
              selector: div.kf-times > span.kf-time
              regex_extract:
                exp: "[0-9]{2}.[0-9]{0,2}$"
            layout: ["15h", "15:04"]
        date_location: CET
        date_language: de_DE
    fetcher:
      type: static

  - name: GaswerkWinterthur
    url: https://www.gaswerk.ch/
    item: div.col-md-7.schedule-wrapper > div.schedule > div.schedule__item
    fields:
      - name: "location"
        value: "Gaswerk"
      - name: "city"
        value: "Winterthur"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.gaswerk.ch/"
      - name: title
        type: text
        location:
          - selector: a.schedule__item__label > p.schedule__item__label__title > span.schedule__item__label__title__act
            all_nodes: true
            separator: ", "
      - name: eventType
        type: text
        location:
          - selector: a.schedule__item__label > p.schedule__item__label__category:nth-child(2)
      - name: url
        type: url
        location:
          - selector: div.collapse.schedule__item__content > div.schedule__item__content__meta:nth-child(3) > ul > li:nth-child(4) > a
            attr: href
            default: https://www.gaswerk.ch/
      - name: genresText
        type: text
        location:
          - selector: a.schedule__item__label > p.schedule__item__label__title > span.schedule__item__label__title__meta:nth-child(2)
            all_nodes: true
            separator: ", "
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.collapse.schedule__item__content > div.schedule__item__content__meta:nth-child(3) > ul > li
            layout:
              - "Türöffnung: 15:04"
          - covers:
              month: true
              day: true
            location:
              selector: a.schedule__item__label > p.schedule__item__label__date
            layout:
              - Mon 2.1
        date_location: CET
        date_language: de_DE
        guess_year: true
    fetcher:
      type: static
    filters:
      - field: eventType
        exp: Kino
        match: false
